// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddResource(arg1) {
  return ObfuscatedCall(0, [arg1]);
}

export function AnalyzeDeps(arg1, arg2, arg3, arg4) {
  return ObfuscatedCall(1, [arg1, arg2, arg3, arg4]);
}

export function AnalyzeResourceDeps(arg1, arg2, arg3) {
  return ObfuscatedCall(2, [arg1, arg2, arg3]);
}

export function Build(arg1) {
  return ObfuscatedCall(3, [arg1]);
}

export function CancelBuild() {
  return ObfuscatedCall(4, []);
}

export function CancelDepsInstall() {
  return ObfuscatedCall(5, []);
}

export function CancelPortableDownload() {
  return ObfuscatedCall(6, []);
}

export function ConfirmExit() {
  return ObfuscatedCall(7, []);
}

export function CreateVenv(arg1, arg2) {
  return ObfuscatedCall(8, [arg1, arg2]);
}

export function DeleteAutoConfig() {
  return ObfuscatedCall(9, []);
}

export function DeletePortablePython(arg1) {
  return ObfuscatedCall(10, [arg1]);
}

export function DetectPythonPath(arg1) {
  return ObfuscatedCall(11, [arg1]);
}

export function DownloadPortablePython(arg1) {
  return ObfuscatedCall(12, [arg1]);
}

export function GetPortablePythons() {
  return ObfuscatedCall(13, []);
}

export function GetPortableRootDir() {
  return ObfuscatedCall(14, []);
}

export function GetPortableVersions() {
  return ObfuscatedCall(15, []);
}

export function GetVersion() {
  return ObfuscatedCall(16, []);
}

export function InstallDeps(arg1, arg2, arg3) {
  return ObfuscatedCall(17, [arg1, arg2, arg3]);
}

export function IsBusy() {
  return ObfuscatedCall(18, []);
}

export function IsExitConfirmed() {
  return ObfuscatedCall(19, []);
}

export function LoadAutoConfig() {
  return ObfuscatedCall(20, []);
}

export function LoadConfigFromFile() {
  return ObfuscatedCall(21, []);
}

export function PreviewCommand(arg1) {
  return ObfuscatedCall(22, [arg1]);
}

export function SaveAutoConfig(arg1) {
  return ObfuscatedCall(23, [arg1]);
}

export function SaveConfigToFile(arg1) {
  return ObfuscatedCall(24, [arg1]);
}

export function ScanResources(arg1) {
  return ObfuscatedCall(25, [arg1]);
}

export function SearchEnvironments(arg1) {
  return ObfuscatedCall(26, [arg1]);
}

export function SelectCustomPython() {
  return ObfuscatedCall(27, []);
}

export function SelectCustomRoot() {
  return ObfuscatedCall(28, []);
}

export function SelectEntryScript() {
  return ObfuscatedCall(29, []);
}

export function SelectIcon() {
  return ObfuscatedCall(30, []);
}

export function SelectOutputDir() {
  return ObfuscatedCall(31, []);
}

export function SelectResourceDir() {
  return ObfuscatedCall(32, []);
}

export function SelectResourceFile() {
  return ObfuscatedCall(33, []);
}
