// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {portable} from '../models';

export function AddResource(arg1:string):Promise<config.ResourceItem>;

export function AnalyzeDeps(arg1:string,arg2:string,arg3:string,arg4:string):Promise<config.DepsResult>;

export function AnalyzeResourceDeps(arg1:string,arg2:string,arg3:Array<config.ResourceItem>):Promise<Array<config.ResourceDep>>;

export function Build(arg1:config.BuildConfig):Promise<void>;

export function CancelBuild():Promise<void>;

export function CancelDepsInstall():Promise<void>;

export function CancelPortableDownload():Promise<void>;

export function ConfirmExit():Promise<void>;

export function CreateVenv(arg1:string,arg2:string):Promise<config.PythonEnv>;

export function DeleteAutoConfig():Promise<void>;

export function DeletePortablePython(arg1:string):Promise<void>;

export function DetectPythonPath(arg1:string):Promise<config.PythonEnv>;

export function DownloadPortablePython(arg1:string):Promise<void>;

export function GetPortablePythons():Promise<Array<portable.PortablePython>>;

export function GetPortableRootDir():Promise<string>;

export function GetPortableVersions():Promise<Array<portable.VersionInfo>>;

export function GetVersion():Promise<string>;

export function InstallDeps(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function IsBusy():Promise<boolean>;

export function IsExitConfirmed():Promise<boolean>;

export function LoadAutoConfig():Promise<config.BuildConfig>;

export function LoadConfigFromFile():Promise<config.BuildConfig>;

export function PreviewCommand(arg1:config.BuildConfig):Promise<string>;

export function SaveAutoConfig(arg1:config.BuildConfig):Promise<void>;

export function SaveConfigToFile(arg1:config.BuildConfig):Promise<string>;

export function ScanResources(arg1:string):Promise<Array<config.ResourceItem>>;

export function SearchEnvironments(arg1:string):Promise<Array<config.PythonEnv>>;

export function SelectCustomPython():Promise<config.PythonEnv>;

export function SelectCustomRoot():Promise<string>;

export function SelectEntryScript():Promise<string>;

export function SelectIcon():Promise<string>;

export function SelectOutputDir():Promise<string>;

export function SelectResourceDir():Promise<string>;

export function SelectResourceFile():Promise<string>;
